on: [push, pull_request]

jobs:
  test_front:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o reposit√≥rio do Git
        uses: actions/checkout@v2
      
      - name: Instala o node
        uses: actions/setup-node@v1
        with:
          node-version: 16
        
      - name: Indo para para pasta dev-repo-web
        run: ls -la
